package view;

import utility.auth.UserManager;

public class AdminHomeFrame extends javax.swing.JFrame {

    public static AdminHomeFrame instance = null;

    public static AdminHomeFrame getInstance() {
        if (instance == null) {
            instance = new AdminHomeFrame();
        }
        return instance;
    }

    private AdminHomeFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnWelcome = new javax.swing.JPanel();
        lbWelcome = new javax.swing.JLabel();
        pnBody = new javax.swing.JPanel();
        btnManager = new javax.swing.JButton();
        btnApp = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bus Manager - Administrator");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnWelcome.setMaximumSize(new java.awt.Dimension(312, 36));
        pnWelcome.setMinimumSize(new java.awt.Dimension(312, 36));
        pnWelcome.setPreferredSize(new java.awt.Dimension(400, 36));

        lbWelcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbWelcome.setText("Welcome, Administrator!");
        lbWelcome.setMaximumSize(new java.awt.Dimension(300, 30));
        lbWelcome.setMinimumSize(new java.awt.Dimension(300, 30));
        lbWelcome.setPreferredSize(new java.awt.Dimension(300, 30));
        pnWelcome.add(lbWelcome);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        getContentPane().add(pnWelcome, gridBagConstraints);

        pnBody.setMaximumSize(new java.awt.Dimension(400, 400));
        pnBody.setMinimumSize(new java.awt.Dimension(400, 400));
        pnBody.setPreferredSize(new java.awt.Dimension(400, 400));
        pnBody.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        btnManager.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManager.setText("Open Manager");
        btnManager.setMaximumSize(new java.awt.Dimension(200, 32));
        btnManager.setMinimumSize(new java.awt.Dimension(200, 32));
        btnManager.setPreferredSize(new java.awt.Dimension(200, 32));
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        pnBody.add(btnManager);

        btnApp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnApp.setText("Open Book Ticket App");
        btnApp.setMaximumSize(new java.awt.Dimension(200, 32));
        btnApp.setMinimumSize(new java.awt.Dimension(200, 32));
        btnApp.setPreferredSize(new java.awt.Dimension(200, 32));
        btnApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppActionPerformed(evt);
            }
        });
        pnBody.add(btnApp);

        btnSettings.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSettings.setText("Language: En");
        btnSettings.setMaximumSize(new java.awt.Dimension(200, 32));
        btnSettings.setMinimumSize(new java.awt.Dimension(200, 32));
        btnSettings.setPreferredSize(new java.awt.Dimension(200, 32));
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        pnBody.add(btnSettings);

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setMaximumSize(new java.awt.Dimension(200, 32));
        btnLogOut.setMinimumSize(new java.awt.Dimension(200, 32));
        btnLogOut.setPreferredSize(new java.awt.Dimension(200, 32));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnBody.add(btnLogOut);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        getContentPane().add(pnBody, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        Manager mng = Manager.getInstance();
        mng.setVisible(true);
    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppActionPerformed
        UserHomeFrame userHomeFrame = UserHomeFrame.getInstance();
        userHomeFrame.setVisible(true);
    }//GEN-LAST:event_btnAppActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        UserManager.getInstance().logout();
        AdminHomeFrame.getInstance().dispose();
        LoginFrame loginFrame = LoginFrame.getInstance();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Manager mng = Manager.getInstance();
            if (mng != null) {
                mng.dispose();
            }
            UserHomeFrame userHomeFrame = UserHomeFrame.getInstance();
            if (userHomeFrame != null) {
                userHomeFrame.dispose();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new AdminHomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApp;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnSettings;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JPanel pnBody;
    private javax.swing.JPanel pnWelcome;
    // End of variables declaration//GEN-END:variables
}
