package view;

import java.util.Locale;

import utility.app.AppTranslator;
import utility.auth.UserManager;
import utility.db.DbConnect;
import utility.auth.Authentication;

public class LoginFrame extends javax.swing.JFrame {
    AppTranslator translator = null;
    private SignUpFrame signUpFrame = null;

    public LoginFrame() {
        translator = AppTranslator.getInstance(Locale.getDefault());
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginPanel = new javax.swing.JPanel();
        lbLogin = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lbSignUp1 = new javax.swing.JLabel();
        lbSignUp2 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        tfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        loginPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        loginPanel.setMinimumSize(new java.awt.Dimension(400, 400));
        loginPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        loginPanel.setLayout(new java.awt.GridBagLayout());

        lbLogin.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogin.setText("Login");
        lbLogin.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(-50, 0, 20, 0);
        loginPanel.add(lbLogin, gridBagConstraints);

        lbUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUser.setText("Username:");
        lbUser.setPreferredSize(new java.awt.Dimension(120, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        loginPanel.add(lbUser, gridBagConstraints);

        lbPass.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPass.setText("Password:");
        lbPass.setPreferredSize(new java.awt.Dimension(120, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        loginPanel.add(lbPass, gridBagConstraints);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLogin.setText("Sign In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        loginPanel.add(btnLogin, gridBagConstraints);

        lbSignUp1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSignUp1.setText("Do not have an account?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, -50, 0, 0);
        loginPanel.add(lbSignUp1, gridBagConstraints);

        lbSignUp2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSignUp2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSignUp2.setText("Sign up");
        lbSignUp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSignUp2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        loginPanel.add(lbSignUp2, gridBagConstraints);

        tfUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUser.setMaximumSize(new java.awt.Dimension(150, 31));
        tfUser.setMinimumSize(new java.awt.Dimension(150, 31));
        tfUser.setPreferredSize(new java.awt.Dimension(150, 31));
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        loginPanel.add(tfUser, gridBagConstraints);

        tfPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPass.setMaximumSize(new java.awt.Dimension(150, 31));
        tfPass.setMinimumSize(new java.awt.Dimension(150, 31));
        tfPass.setPreferredSize(new java.awt.Dimension(150, 31));
        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        loginPanel.add(tfPass, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(loginPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = tfUser.getText().trim();
        String password = new String(tfPass.getPassword()).trim();
        if (username.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, translator.translate("login.error.invalid"),
                translator.translate("login.error.title"), javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Authentication.login(username, password)) {      
            UserManager userManager = UserManager.getInstance();
            userManager.login(username, password);
            if (userManager.getCurrentUser() != null && userManager.getCurrentUser().getRole().equals("admin")) {
                AdminHomeFrame adminHomeFrame = AdminHomeFrame.getInstance();
                if (adminHomeFrame != null) {
                    adminHomeFrame.setVisible(true);
                }
            } else if (userManager.getCurrentUser() != null) {
                UserHomeFrame userHomeFrame = UserHomeFrame.getInstance();
                if (userHomeFrame != null) {
                    userHomeFrame.setVisible(true);
                }
            }
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, translator.translate("login.invalid"),
                translator.translate("login.error.title"), javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lbSignUp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSignUp2MouseClicked
        signUpFrame = SignUpFrame.getInstance();
        if (signUpFrame != null){
            signUpFrame.setVisible(true);
        }
    }//GEN-LAST:event_lbSignUp2MouseClicked

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        tfPass.requestFocus();
    }//GEN-LAST:event_tfUserActionPerformed

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        btnLoginActionPerformed(evt);
    }//GEN-LAST:event_tfPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            DbConnect.getInstance();
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginFrame().setVisible(true);
                }
            });
        } catch (RuntimeException ex) {
            AppTranslator translator = AppTranslator.getInstance(Locale.ENGLISH);
            javax.swing.JOptionPane.showMessageDialog(
                null,
                translator.translate("db.connection.error"),
                "db.connection.title_error", 
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            System.exit(1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbSignUp1;
    private javax.swing.JLabel lbSignUp2;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
