package view;

import java.util.Locale;
import javax.swing.JOptionPane;

import utility.AppTranslator;
import utility.Authentication;

public class SignUpFrame extends javax.swing.JFrame {
    AppTranslator translator;
    private boolean isShowPass = false;
    private boolean isUserOK = false;
    private boolean isPassOK = false;
    private static SignUpFrame instance = null;
    private SignUpFrame() {
        translator = AppTranslator.getInstance(new Locale("en"));
        initComponents();
        setLocationRelativeTo(null);
    }

    public static SignUpFrame getInstance() {
        if (instance == null) {
            instance = new SignUpFrame();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbSignUp = new javax.swing.JLabel();
        pnSignUp = new javax.swing.JScrollPane();
        pnSignUpDetaiil = new javax.swing.JPanel();
        lbFirstName = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        tfPass = new javax.swing.JPasswordField();
        lbPass = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        lbCheckUser = new javax.swing.JLabel();
        lbCheckPass1 = new javax.swing.JLabel();
        lbCheckPass2 = new javax.swing.JLabel();
        btnShowHide = new javax.swing.JButton();
        lbUser = new javax.swing.JLabel();
        tfPhone = new javax.swing.JTextField();
        lbLastName = new javax.swing.JLabel();
        lbDoB = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        lbPhone = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        lbCheckEmail = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Up");
        setMaximumSize(new java.awt.Dimension(400, 600));
        setMinimumSize(new java.awt.Dimension(400, 600));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        lbSignUp.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSignUp.setText("Sign Up");
        getContentPane().add(lbSignUp);

        pnSignUp.setMaximumSize(new java.awt.Dimension(360, 400));
        pnSignUp.setMinimumSize(new java.awt.Dimension(360, 400));
        pnSignUp.setPreferredSize(new java.awt.Dimension(360, 400));

        pnSignUpDetaiil.setMaximumSize(new java.awt.Dimension(350, 120));
        pnSignUpDetaiil.setMinimumSize(new java.awt.Dimension(350, 120));
        pnSignUpDetaiil.setPreferredSize(new java.awt.Dimension(350, 120));
        pnSignUpDetaiil.setLayout(new java.awt.GridBagLayout());

        lbFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFirstName.setText("First name:");
        lbFirstName.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnSignUpDetaiil.add(lbFirstName, gridBagConstraints);

        tfUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfUser.setMinimumSize(new java.awt.Dimension(150, 32));
        tfUser.setPreferredSize(new java.awt.Dimension(200, 32));
        tfUser.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfUserCaretUpdate(evt);
            }
        });
        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnSignUpDetaiil.add(tfUser, gridBagConstraints);

        tfPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPass.setMinimumSize(new java.awt.Dimension(200, 32));
        tfPass.setPreferredSize(new java.awt.Dimension(200, 32));
        tfPass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfPassCaretUpdate(evt);
            }
        });
        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnSignUpDetaiil.add(tfPass, gridBagConstraints);

        lbPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPass.setText("Password:");
        lbPass.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnSignUpDetaiil.add(lbPass, gridBagConstraints);

        tfFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfFirstName.setMinimumSize(new java.awt.Dimension(150, 32));
        tfFirstName.setName(""); // NOI18N
        tfFirstName.setPreferredSize(new java.awt.Dimension(200, 32));
        tfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnSignUpDetaiil.add(tfFirstName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        pnSignUpDetaiil.add(lbCheckUser, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        pnSignUpDetaiil.add(lbCheckPass1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        pnSignUpDetaiil.add(lbCheckPass2, gridBagConstraints);

        btnShowHide.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        btnShowHide.setText("S");
        btnShowHide.setToolTipText("Show");
        btnShowHide.setMaximumSize(new java.awt.Dimension(36, 32));
        btnShowHide.setMinimumSize(new java.awt.Dimension(36, 32));
        btnShowHide.setPreferredSize(new java.awt.Dimension(36, 32));
        btnShowHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowHideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        pnSignUpDetaiil.add(btnShowHide, gridBagConstraints);

        lbUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUser.setText("Username:");
        lbUser.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnSignUpDetaiil.add(lbUser, gridBagConstraints);

        tfPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPhone.setMinimumSize(new java.awt.Dimension(150, 32));
        tfPhone.setName(""); // NOI18N
        tfPhone.setPreferredSize(new java.awt.Dimension(200, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnSignUpDetaiil.add(tfPhone, gridBagConstraints);

        lbLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbLastName.setText("Last name:");
        lbLastName.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnSignUpDetaiil.add(lbLastName, gridBagConstraints);

        lbDoB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbDoB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDoB.setText("Date of Birth:");
        lbDoB.setMaximumSize(new java.awt.Dimension(120, 25));
        lbDoB.setMinimumSize(new java.awt.Dimension(120, 25));
        lbDoB.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, -200, 0, 0);
        pnSignUpDetaiil.add(lbDoB, gridBagConstraints);

        dateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateChooser.setMaximumSize(new java.awt.Dimension(180, 32));
        dateChooser.setMinimumSize(new java.awt.Dimension(180, 32));
        dateChooser.setPreferredSize(new java.awt.Dimension(180, 32));
        dateChooser.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        pnSignUpDetaiil.add(dateChooser, gridBagConstraints);

        lbPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPhone.setText("Phone");
        lbPhone.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnSignUpDetaiil.add(lbPhone, gridBagConstraints);

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfEmail.setMinimumSize(new java.awt.Dimension(150, 32));
        tfEmail.setName(""); // NOI18N
        tfEmail.setPreferredSize(new java.awt.Dimension(200, 32));
        tfEmail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfEmailCaretUpdate(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnSignUpDetaiil.add(tfEmail, gridBagConstraints);

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEmail.setText("Email");
        lbEmail.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnSignUpDetaiil.add(lbEmail, gridBagConstraints);

        tfLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfLastName.setMinimumSize(new java.awt.Dimension(150, 32));
        tfLastName.setName(""); // NOI18N
        tfLastName.setPreferredSize(new java.awt.Dimension(200, 32));
        tfLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLastNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnSignUpDetaiil.add(tfLastName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        pnSignUpDetaiil.add(lbCheckEmail, gridBagConstraints);

        pnSignUp.setViewportView(pnSignUpDetaiil);

        getContentPane().add(pnSignUp);

        btnSignUp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        tfFirstName.requestFocus();
    }//GEN-LAST:event_tfUserActionPerformed

    private void tfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstNameActionPerformed
        tfLastName.requestFocus();
    }//GEN-LAST:event_tfFirstNameActionPerformed

    private void tfLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLastNameActionPerformed
        tfPass.requestFocus();
    }//GEN-LAST:event_tfLastNameActionPerformed

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        btnSignUp.requestFocus();
    }//GEN-LAST:event_tfPassActionPerformed

    private void tfUserCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfUserCaretUpdate
        String user = tfUser.getText();
        if (user.length() < 4) {
            lbCheckUser.setText(translator.translate("signup.username.invalid1"));
            lbCheckUser.setForeground(java.awt.Color.RED);
        } else if (!user.matches("^[a-zA-Z0-9_]+$")) {
            lbCheckUser.setText(translator.translate("signup.username.invalid2"));
            lbCheckUser.setForeground(java.awt.Color.RED);
        } else {
            lbCheckUser.setText(translator.translate("signup.username.valid"));
            lbCheckUser.setForeground(java.awt.Color.GREEN);
            isUserOK = true;
        }
        if (Authentication.userExists(user)) {
            lbCheckUser.setText(translator.translate("signup.username.invalid3"));
            lbCheckUser.setForeground(java.awt.Color.RED);
            isUserOK = false;
        }
    }//GEN-LAST:event_tfUserCaretUpdate

    private void btnShowHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowHideActionPerformed
        isShowPass = !isShowPass;
        if (isShowPass) {
            btnShowHide.setText(translator.translate("btn.hide.shortcut"));
            btnShowHide.setToolTipText(translator.translate("btn.hide"));
            tfPass.setEchoChar((char) 0);
        } else {
            btnShowHide.setText(translator.translate("btn.show.shortcut"));
            btnShowHide.setToolTipText(translator.translate("btn.show"));
            tfPass.setEchoChar('*');
        }
    }//GEN-LAST:event_btnShowHideActionPerformed

    private void tfPassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfPassCaretUpdate
        String pass = String.valueOf(tfPass.getPassword());
        if (pass.length() < 8) {
            lbCheckPass1.setText(translator.translate("signup.password.invalid1"));
            lbCheckPass1.setForeground(java.awt.Color.RED);
            lbCheckPass2.setText("");
        } else if (!pass.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]+$")) {
            lbCheckPass1.setText(translator.translate("signup.password.invalid2"));
            lbCheckPass1.setForeground(java.awt.Color.RED);
            lbCheckPass2.setText(translator.translate("signup.password.invalid3"));
            lbCheckPass2.setForeground(java.awt.Color.RED);
        } else {
            lbCheckPass1.setText(translator.translate("signup.password.valid"));
            lbCheckPass1.setForeground(java.awt.Color.GREEN);
            lbCheckPass2.setText("");
            isPassOK = true;
        }
    }//GEN-LAST:event_tfPassCaretUpdate

    private void tfEmailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfEmailCaretUpdate
        
    }//GEN-LAST:event_tfEmailCaretUpdate

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        String user = tfUser.getText().trim();
        String pass = String.valueOf(tfPass.getPassword()).trim();
        // String firstName = tfFirstName.getText().trim();
        // String lastName = tfLastName.getText().trim();
        // String dob = (dateChooser.getDate() != null) ?
        //         new java.text.SimpleDateFormat("yyyy-MM-dd").format(dateChooser.getDate()) : "";
        // String phone = tfPhone.getText().trim();
        String email = tfEmail.getText().trim();
        String role = "user";
        if (!isUserOK || !isPassOK) {
            JOptionPane.showMessageDialog(this, translator.translate("signup.error.invalid"), 
                    translator.translate("signup.error.title"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Authentication.register(user, pass, email, role)) {
            JOptionPane.showMessageDialog(this, translator.translate("signup.success"), 
                    translator.translate("signup.success.title"), JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, translator.translate("signup.username.invalid3"), 
                    translator.translate("signup.error.title"), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowHide;
    private javax.swing.JButton btnSignUp;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel lbCheckEmail;
    private javax.swing.JLabel lbCheckPass1;
    private javax.swing.JLabel lbCheckPass2;
    private javax.swing.JLabel lbCheckUser;
    private javax.swing.JLabel lbDoB;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbSignUp;
    private javax.swing.JLabel lbUser;
    private javax.swing.JScrollPane pnSignUp;
    private javax.swing.JPanel pnSignUpDetaiil;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
