package view;

import utility.auth.UserManager;

public class UserHomeFrame extends javax.swing.JFrame {

    public static UserHomeFrame instance = null;
    
    public static UserHomeFrame getInstance() {
        if (instance == null) {
            instance = new UserHomeFrame();
        }
        return instance;
    }

    public String getUser() {
        UserManager um = UserManager.getInstance();
        if (um.isLoggedIn()) {
            return um.getUserName();
        }
        return "Guest";
    }

    private UserHomeFrame() {
        initComponents();
        setLocationRelativeTo(null);
        pnHome.setVisible(true);
        pnNotifications.setVisible(false);
        pnSettings.setVisible(false);
        lbHomeWelcome.setText("Welcome, " + getUser() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnApp = new javax.swing.JPanel();
        pnHome = new javax.swing.JPanel();
        pnAppNotifications = new javax.swing.JPanel();
        lbAppNotifications = new javax.swing.JLabel();
        pnUser = new javax.swing.JPanel();
        lbHomeWelcome = new javax.swing.JLabel();
        lbAddPhotoProfile = new javax.swing.JLabel();
        lbEditProfile = new javax.swing.JLabel();
        pnAction = new javax.swing.JPanel();
        btnSearchRoute = new javax.swing.JButton();
        btnBookTicket = new javax.swing.JButton();
        btnViewRoute = new javax.swing.JButton();
        btnBookingHistory = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        pnHomeHolder = new javax.swing.JPanel();
        pnNotifications = new javax.swing.JPanel();
        lbUserNotifications = new javax.swing.JLabel();
        pnNotifCategory = new javax.swing.JPanel();
        cbNotifCategory = new javax.swing.JComboBox<>();
        spnNotifDetail = new javax.swing.JScrollPane();
        pnNotifDetail = new javax.swing.JPanel();
        pnSettings = new javax.swing.JPanel();
        lbAppSettings = new javax.swing.JLabel();
        pnSettingButtons = new javax.swing.JPanel();
        btnAccSetting = new javax.swing.JButton();
        btnNotifSetting = new javax.swing.JButton();
        btnTravelPreSetting = new javax.swing.JButton();
        btnPaymentSetting = new javax.swing.JButton();
        btnLanguageSetting = new javax.swing.JButton();
        btnPrivacySetting = new javax.swing.JButton();
        btnHelpSetting = new javax.swing.JButton();
        pnNavigationIcon = new javax.swing.JPanel();
        btnHomeNav = new javax.swing.JButton();
        btnNotificationsNav = new javax.swing.JButton();
        btnSettingsNav = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bus Ticket Booking App");
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnApp.setBackground(new java.awt.Color(150, 188, 255));
        pnApp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnApp.setMaximumSize(new java.awt.Dimension(1260, 640));
        pnApp.setMinimumSize(new java.awt.Dimension(1260, 640));
        pnApp.setPreferredSize(new java.awt.Dimension(1260, 640));
        pnApp.setLayout(new java.awt.CardLayout(2, 2));

        pnHome.setMaximumSize(new java.awt.Dimension(1200, 600));
        pnHome.setMinimumSize(new java.awt.Dimension(1200, 600));
        pnHome.setPreferredSize(new java.awt.Dimension(1200, 600));
        pnHome.setLayout(new java.awt.GridBagLayout());

        pnAppNotifications.setMaximumSize(new java.awt.Dimension(1200, 60));
        pnAppNotifications.setMinimumSize(new java.awt.Dimension(1200, 60));
        pnAppNotifications.setPreferredSize(new java.awt.Dimension(1200, 60));
        pnAppNotifications.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));

        lbAppNotifications.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAppNotifications.setText("Notification");
        lbAppNotifications.setMaximumSize(new java.awt.Dimension(1100, 60));
        lbAppNotifications.setMinimumSize(new java.awt.Dimension(1100, 60));
        lbAppNotifications.setPreferredSize(new java.awt.Dimension(1100, 60));
        pnAppNotifications.add(lbAppNotifications);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        pnHome.add(pnAppNotifications, gridBagConstraints);

        pnUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnUser.setMinimumSize(new java.awt.Dimension(300, 300));
        pnUser.setPreferredSize(new java.awt.Dimension(300, 300));
        pnUser.setLayout(new java.awt.GridBagLayout());

        lbHomeWelcome.setBackground(new java.awt.Color(255, 255, 255));
        lbHomeWelcome.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbHomeWelcome.setForeground(new java.awt.Color(15, 45, 255));
        lbHomeWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHomeWelcome.setText("Welcome, user!");
        lbHomeWelcome.setMaximumSize(new java.awt.Dimension(300, 48));
        lbHomeWelcome.setMinimumSize(new java.awt.Dimension(300, 48));
        lbHomeWelcome.setPreferredSize(new java.awt.Dimension(300, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnUser.add(lbHomeWelcome, gridBagConstraints);

        lbAddPhotoProfile.setBackground(new java.awt.Color(255, 255, 255));
        lbAddPhotoProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbAddPhotoProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAddPhotoProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_photo.png"))); // NOI18N
        lbAddPhotoProfile.setText("Add photo");
        lbAddPhotoProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAddPhotoProfile.setMaximumSize(new java.awt.Dimension(150, 150));
        lbAddPhotoProfile.setMinimumSize(new java.awt.Dimension(150, 150));
        lbAddPhotoProfile.setPreferredSize(new java.awt.Dimension(150, 150));
        lbAddPhotoProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAddPhotoProfileMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnUser.add(lbAddPhotoProfile, gridBagConstraints);

        lbEditProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEditProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEditProfile.setText("Edit profile");
        lbEditProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbEditProfile.setMaximumSize(new java.awt.Dimension(100, 32));
        lbEditProfile.setMinimumSize(new java.awt.Dimension(100, 32));
        lbEditProfile.setPreferredSize(new java.awt.Dimension(100, 32));
        lbEditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEditProfileMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        pnUser.add(lbEditProfile, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnHome.add(pnUser, gridBagConstraints);

        pnAction.setMinimumSize(new java.awt.Dimension(600, 300));
        pnAction.setPreferredSize(new java.awt.Dimension(600, 300));
        pnAction.setLayout(new java.awt.GridBagLayout());

        btnSearchRoute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchRoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnSearchRoute.setText("Search Route");
        btnSearchRoute.setMaximumSize(new java.awt.Dimension(160, 80));
        btnSearchRoute.setMinimumSize(new java.awt.Dimension(160, 80));
        btnSearchRoute.setPreferredSize(new java.awt.Dimension(160, 80));
        btnSearchRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRouteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnAction.add(btnSearchRoute, gridBagConstraints);

        btnBookTicket.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBookTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_ticket.png"))); // NOI18N
        btnBookTicket.setText("Book Ticket");
        btnBookTicket.setMaximumSize(new java.awt.Dimension(160, 80));
        btnBookTicket.setMinimumSize(new java.awt.Dimension(160, 80));
        btnBookTicket.setPreferredSize(new java.awt.Dimension(160, 80));
        btnBookTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookTicketActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnAction.add(btnBookTicket, gridBagConstraints);

        btnViewRoute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnViewRoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus_view_route.png"))); // NOI18N
        btnViewRoute.setText("View Route");
        btnViewRoute.setMaximumSize(new java.awt.Dimension(160, 80));
        btnViewRoute.setMinimumSize(new java.awt.Dimension(160, 80));
        btnViewRoute.setPreferredSize(new java.awt.Dimension(160, 80));
        btnViewRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRouteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnAction.add(btnViewRoute, gridBagConstraints);

        btnBookingHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBookingHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        btnBookingHistory.setText("Booking History");
        btnBookingHistory.setMaximumSize(new java.awt.Dimension(160, 80));
        btnBookingHistory.setMinimumSize(new java.awt.Dimension(160, 80));
        btnBookingHistory.setPreferredSize(new java.awt.Dimension(160, 80));
        btnBookingHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingHistoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnAction.add(btnBookingHistory, gridBagConstraints);

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log_out.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setMaximumSize(new java.awt.Dimension(160, 40));
        btnLogOut.setMinimumSize(new java.awt.Dimension(160, 40));
        btnLogOut.setPreferredSize(new java.awt.Dimension(160, 40));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnAction.add(btnLogOut, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pnHome.add(pnAction, gridBagConstraints);

        pnHomeHolder.setMinimumSize(new java.awt.Dimension(1200, 200));
        pnHomeHolder.setPreferredSize(new java.awt.Dimension(1200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        pnHome.add(pnHomeHolder, gridBagConstraints);

        pnApp.add(pnHome, "card2");

        pnNotifications.setMaximumSize(new java.awt.Dimension(1200, 600));
        pnNotifications.setMinimumSize(new java.awt.Dimension(1200, 600));
        pnNotifications.setPreferredSize(new java.awt.Dimension(1200, 600));
        pnNotifications.setLayout(new java.awt.GridBagLayout());

        lbUserNotifications.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbUserNotifications.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUserNotifications.setText("Notifications");
        lbUserNotifications.setMaximumSize(new java.awt.Dimension(200, 40));
        lbUserNotifications.setMinimumSize(new java.awt.Dimension(200, 40));
        lbUserNotifications.setPreferredSize(new java.awt.Dimension(200, 40));
        pnNotifications.add(lbUserNotifications, new java.awt.GridBagConstraints());

        pnNotifCategory.setMaximumSize(new java.awt.Dimension(200, 50));
        pnNotifCategory.setMinimumSize(new java.awt.Dimension(200, 50));
        pnNotifCategory.setPreferredSize(new java.awt.Dimension(200, 50));
        pnNotifCategory.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cbNotifCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbNotifCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Seen", "Important" }));
        cbNotifCategory.setMaximumSize(new java.awt.Dimension(150, 40));
        cbNotifCategory.setMinimumSize(new java.awt.Dimension(150, 40));
        cbNotifCategory.setPreferredSize(new java.awt.Dimension(150, 40));
        pnNotifCategory.add(cbNotifCategory);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 700, 0, 0);
        pnNotifications.add(pnNotifCategory, gridBagConstraints);

        spnNotifDetail.setMaximumSize(new java.awt.Dimension(1000, 500));
        spnNotifDetail.setMinimumSize(new java.awt.Dimension(1000, 500));
        spnNotifDetail.setPreferredSize(new java.awt.Dimension(1000, 500));
        spnNotifDetail.setViewportView(pnNotifDetail);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnNotifications.add(spnNotifDetail, gridBagConstraints);

        pnApp.add(pnNotifications, "card3");

        pnSettings.setMaximumSize(new java.awt.Dimension(1200, 600));
        pnSettings.setMinimumSize(new java.awt.Dimension(1200, 600));
        pnSettings.setPreferredSize(new java.awt.Dimension(1200, 600));
        pnSettings.setLayout(new java.awt.GridBagLayout());

        lbAppSettings.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbAppSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAppSettings.setText("Settings");
        lbAppSettings.setMaximumSize(new java.awt.Dimension(200, 40));
        lbAppSettings.setMinimumSize(new java.awt.Dimension(200, 40));
        lbAppSettings.setPreferredSize(new java.awt.Dimension(200, 40));
        pnSettings.add(lbAppSettings, new java.awt.GridBagConstraints());

        pnSettingButtons.setMinimumSize(new java.awt.Dimension(1000, 500));
        pnSettingButtons.setPreferredSize(new java.awt.Dimension(1000, 500));
        pnSettingButtons.setLayout(new java.awt.GridBagLayout());

        btnAccSetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAccSetting.setText("Account");
        btnAccSetting.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAccSetting.setMinimumSize(new java.awt.Dimension(200, 40));
        btnAccSetting.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnSettingButtons.add(btnAccSetting, gridBagConstraints);

        btnNotifSetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNotifSetting.setText("Notifications");
        btnNotifSetting.setMaximumSize(new java.awt.Dimension(200, 40));
        btnNotifSetting.setMinimumSize(new java.awt.Dimension(200, 40));
        btnNotifSetting.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnSettingButtons.add(btnNotifSetting, gridBagConstraints);

        btnTravelPreSetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTravelPreSetting.setText("Travel Preferences");
        btnTravelPreSetting.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTravelPreSetting.setMinimumSize(new java.awt.Dimension(200, 40));
        btnTravelPreSetting.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnSettingButtons.add(btnTravelPreSetting, gridBagConstraints);

        btnPaymentSetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPaymentSetting.setText("Payment");
        btnPaymentSetting.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPaymentSetting.setMinimumSize(new java.awt.Dimension(200, 40));
        btnPaymentSetting.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnSettingButtons.add(btnPaymentSetting, gridBagConstraints);

        btnLanguageSetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLanguageSetting.setText("Language");
        btnLanguageSetting.setMaximumSize(new java.awt.Dimension(200, 40));
        btnLanguageSetting.setMinimumSize(new java.awt.Dimension(200, 40));
        btnLanguageSetting.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnSettingButtons.add(btnLanguageSetting, gridBagConstraints);

        btnPrivacySetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrivacySetting.setText("Privacy");
        btnPrivacySetting.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPrivacySetting.setMinimumSize(new java.awt.Dimension(200, 40));
        btnPrivacySetting.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnSettingButtons.add(btnPrivacySetting, gridBagConstraints);

        btnHelpSetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHelpSetting.setText("Help");
        btnHelpSetting.setMaximumSize(new java.awt.Dimension(200, 40));
        btnHelpSetting.setMinimumSize(new java.awt.Dimension(200, 40));
        btnHelpSetting.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        pnSettingButtons.add(btnHelpSetting, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnSettings.add(pnSettingButtons, gridBagConstraints);

        pnApp.add(pnSettings, "card4");

        getContentPane().add(pnApp, new java.awt.GridBagConstraints());

        pnNavigationIcon.setBackground(new java.awt.Color(150, 188, 255));
        pnNavigationIcon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnNavigationIcon.setMaximumSize(new java.awt.Dimension(1260, 50));
        pnNavigationIcon.setMinimumSize(new java.awt.Dimension(1260, 50));
        pnNavigationIcon.setPreferredSize(new java.awt.Dimension(1260, 50));
        pnNavigationIcon.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 0));

        btnHomeNav.setText("Home");
        btnHomeNav.setMaximumSize(new java.awt.Dimension(410, 40));
        btnHomeNav.setMinimumSize(new java.awt.Dimension(410, 40));
        btnHomeNav.setPreferredSize(new java.awt.Dimension(410, 40));
        btnHomeNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeNavActionPerformed(evt);
            }
        });
        pnNavigationIcon.add(btnHomeNav);

        btnNotificationsNav.setText("Notifications");
        btnNotificationsNav.setMaximumSize(new java.awt.Dimension(410, 40));
        btnNotificationsNav.setMinimumSize(new java.awt.Dimension(410, 40));
        btnNotificationsNav.setPreferredSize(new java.awt.Dimension(410, 40));
        btnNotificationsNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificationsNavActionPerformed(evt);
            }
        });
        pnNavigationIcon.add(btnNotificationsNav);

        btnSettingsNav.setText("Settings");
        btnSettingsNav.setMaximumSize(new java.awt.Dimension(410, 40));
        btnSettingsNav.setMinimumSize(new java.awt.Dimension(410, 40));
        btnSettingsNav.setPreferredSize(new java.awt.Dimension(410, 40));
        btnSettingsNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsNavActionPerformed(evt);
            }
        });
        pnNavigationIcon.add(btnSettingsNav);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(pnNavigationIcon, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeNavActionPerformed
        pnHome.setVisible(true);
        pnNotifications.setVisible(false);
        pnSettings.setVisible(false);
    }//GEN-LAST:event_btnHomeNavActionPerformed

    private void btnNotificationsNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationsNavActionPerformed
        pnHome.setVisible(false);
        pnNotifications.setVisible(true);
        pnSettings.setVisible(false);    
    }//GEN-LAST:event_btnNotificationsNavActionPerformed

    private void btnSettingsNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsNavActionPerformed
        pnHome.setVisible(false);
        pnNotifications.setVisible(false);
        pnSettings.setVisible(true);
    }//GEN-LAST:event_btnSettingsNavActionPerformed

    private void btnSearchRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRouteActionPerformed
        
    }//GEN-LAST:event_btnSearchRouteActionPerformed

    private void btnBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicketActionPerformed
        
    }//GEN-LAST:event_btnBookTicketActionPerformed

    private void btnViewRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRouteActionPerformed
        
    }//GEN-LAST:event_btnViewRouteActionPerformed

    private void btnBookingHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingHistoryActionPerformed
        
    }//GEN-LAST:event_btnBookingHistoryActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void lbAddPhotoProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAddPhotoProfileMouseClicked
        
    }//GEN-LAST:event_lbAddPhotoProfileMouseClicked

    private void lbEditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEditProfileMouseClicked
        
    }//GEN-LAST:event_lbEditProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                 new UserHomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccSetting;
    private javax.swing.JButton btnBookTicket;
    private javax.swing.JButton btnBookingHistory;
    private javax.swing.JButton btnHelpSetting;
    private javax.swing.JButton btnHomeNav;
    private javax.swing.JButton btnLanguageSetting;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNotifSetting;
    private javax.swing.JButton btnNotificationsNav;
    private javax.swing.JButton btnPaymentSetting;
    private javax.swing.JButton btnPrivacySetting;
    private javax.swing.JButton btnSearchRoute;
    private javax.swing.JButton btnSettingsNav;
    private javax.swing.JButton btnTravelPreSetting;
    private javax.swing.JButton btnViewRoute;
    private javax.swing.JComboBox<String> cbNotifCategory;
    private javax.swing.JLabel lbAddPhotoProfile;
    private javax.swing.JLabel lbAppNotifications;
    private javax.swing.JLabel lbAppSettings;
    private javax.swing.JLabel lbEditProfile;
    private javax.swing.JLabel lbHomeWelcome;
    private javax.swing.JLabel lbUserNotifications;
    private javax.swing.JPanel pnAction;
    private javax.swing.JPanel pnApp;
    private javax.swing.JPanel pnAppNotifications;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnHomeHolder;
    private javax.swing.JPanel pnNavigationIcon;
    private javax.swing.JPanel pnNotifCategory;
    private javax.swing.JPanel pnNotifDetail;
    private javax.swing.JPanel pnNotifications;
    private javax.swing.JPanel pnSettingButtons;
    private javax.swing.JPanel pnSettings;
    private javax.swing.JPanel pnUser;
    private javax.swing.JScrollPane spnNotifDetail;
    // End of variables declaration//GEN-END:variables
}
